import type { Octokit } from "@octokit/core";
import sodium from "libsodium-wrappers";

const WORKFLOW_PATH = ".github/workflows/feedbackiq.yml";
const SECRET_NAME = "FEEDBACKIQ_ANTHROPIC_KEY";

function buildWorkflowYaml(): string {
  return `name: FeedbackIQ Agent
on:
  workflow_dispatch:
    inputs:
      feedback_id:
        required: true
      feedback_content:
        required: true
      source_url:
        required: false
        default: ''
      default_branch:
        required: true
      callback_url:
        required: true
      callback_secret:
        required: true
      installation_token:
        required: true

jobs:
  generate-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: \${{ inputs.installation_token }}

      - name: Prepare branch and prompt
        id: prep
        env:
          FEEDBACK_ID: \${{ inputs.feedback_id }}
          FEEDBACK_CONTENT: \${{ inputs.feedback_content }}
          SOURCE_URL: \${{ inputs.source_url }}
        run: |
          set -euo pipefail
          BRANCH="feedbackiq/feedback-\${FEEDBACK_ID:0:8}"
          git config user.name FeedbackIQ
          git config user.email bot@feedbackiq.app
          git checkout -b "$BRANCH"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

          {
            echo "You are an automated code agent running in a GitHub Actions workflow to address user feedback by making minimal, focused code changes."
            echo ""
            echo "You are in a fresh checkout of the repository's default branch. Edit files directly. Do not run dev servers, tests, or anything that requires network access beyond reading code."
            echo ""
            echo "Use Grep and Glob to locate relevant code before reading files. Do not speculatively read many files."
            echo ""
            echo "Make the smallest change that addresses the feedback. Keep to a handful of files. Do not refactor unrelated code. Do not add comments explaining the change. Do not format the whole file."
            echo ""
            echo "When you are finished, write a short (1-3 sentence) human-readable summary of what you changed to /tmp/pr_summary.txt. Do not include a title or code blocks in the summary."
            echo ""
            echo "=== USER FEEDBACK ==="
            printf '%s\\n' "$FEEDBACK_CONTENT"
            echo "=== END FEEDBACK ==="
            if [ -n "$SOURCE_URL" ]; then
              echo ""
              echo "Source URL: $SOURCE_URL"
            fi
          } > /tmp/prompt.md

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-base-action@v0.0.63
        with:
          anthropic_api_key: \${{ secrets.FEEDBACKIQ_ANTHROPIC_KEY }}
          prompt_file: /tmp/prompt.md
          max_turns: "25"
          allowed_tools: "Read,Edit,Write,MultiEdit,Grep,Glob,TodoWrite,Bash(git diff:*),Bash(ls:*)"
          timeout_minutes: "20"

      - name: Commit, push, create PR
        id: pr
        env:
          GH_TOKEN: \${{ inputs.installation_token }}
          FEEDBACK_CONTENT: \${{ inputs.feedback_content }}
          SOURCE_URL: \${{ inputs.source_url }}
          DEFAULT_BRANCH: \${{ inputs.default_branch }}
          BRANCH: \${{ steps.prep.outputs.branch }}
        run: |
          set -euo pipefail
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes made by agent"
            echo "status=no_changes" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          SUMMARY=""
          if [ -f /tmp/pr_summary.txt ]; then
            SUMMARY=$(cat /tmp/pr_summary.txt)
          fi
          if [ -z "$SUMMARY" ]; then
            SUMMARY="Changes proposed by the FeedbackIQ agent."
          fi

          git add -A
          git commit -m "[FeedbackIQ] Address feedback"
          git push --force origin "$BRANCH"

          {
            echo "## Feedback"
            echo ""
            printf '%s\\n' "$FEEDBACK_CONTENT"
            if [ -n "$SOURCE_URL" ]; then
              echo ""
              echo "**Source:** $SOURCE_URL"
            fi
            echo ""
            echo "## Changes"
            echo ""
            printf '%s\\n' "$SUMMARY"
            echo ""
            echo "---"
            echo "*Auto-generated by [FeedbackIQ](https://feedbackiq.app)*"
          } > /tmp/pr_body.md

          EXISTING_PR=$(gh pr list --head "$BRANCH" --state open --json url,number --limit 1)
          EXISTING_URL=$(echo "$EXISTING_PR" | jq -r '.[0].url // ""')
          if [ -n "$EXISTING_URL" ]; then
            PR_URL="$EXISTING_URL"
            gh pr edit "$PR_URL" --body-file /tmp/pr_body.md >/dev/null
          else
            PR_URL=$(gh pr create --title "[FeedbackIQ] Address feedback" --body-file /tmp/pr_body.md --base "$DEFAULT_BRANCH" --head "$BRANCH")
          fi
          echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
          NUM=$(echo "$PR_URL" | grep -oE '/pull/[0-9]+$' | grep -oE '[0-9]+$' || echo "")
          echo "pr_number=$NUM" >> "$GITHUB_OUTPUT"
          echo "status=pr_created" >> "$GITHUB_OUTPUT"

      - name: Callback
        if: always()
        env:
          FEEDBACK_ID: \${{ inputs.feedback_id }}
          CALLBACK_URL: \${{ inputs.callback_url }}
          CALLBACK_SECRET: \${{ inputs.callback_secret }}
          BRANCH: \${{ steps.prep.outputs.branch }}
          PR_STATUS: \${{ steps.pr.outputs.status }}
          PR_URL: \${{ steps.pr.outputs.pr_url }}
          PR_NUMBER: \${{ steps.pr.outputs.pr_number }}
          CLAUDE_CONCLUSION: \${{ steps.claude.outputs.conclusion }}
        run: |
          set -u
          if [ "\${PR_STATUS:-}" = "pr_created" ]; then
            BODY=$(jq -n \\
              --arg fid "$FEEDBACK_ID" \\
              --arg url "$PR_URL" \\
              --arg branch "$BRANCH" \\
              --argjson num "\${PR_NUMBER:-null}" \\
              '{feedback_id:$fid, status:"pr_created", pr_url:$url, pr_number:$num, branch_name:$branch}')
          else
            BODY=$(jq -n \\
              --arg fid "$FEEDBACK_ID" \\
              --arg log "claude conclusion: \${CLAUDE_CONCLUSION:-unknown}; pr step: \${PR_STATUS:-unknown}" \\
              '{feedback_id:$fid, status:"closed", agent_log:$log}')
          fi
          curl -sS -X POST "$CALLBACK_URL" \\
            -H "Content-Type: application/json" \\
            -H "X-FeedbackIQ-Secret: $CALLBACK_SECRET" \\
            -d "$BODY" || true
`;
}

export async function ensureWorkflowInstalled(
  octokit: Octokit,
  owner: string,
  repo: string,
  defaultBranch: string
): Promise<boolean> {
  const desiredContent = buildWorkflowYaml();
  const desiredBase64 = Buffer.from(desiredContent).toString("base64");

  let existingSha: string | null = null;
  let existingContent: string | null = null;
  try {
    const { data } = await octokit.request(
      "GET /repos/{owner}/{repo}/contents/{path}",
      { owner, repo, path: WORKFLOW_PATH, ref: defaultBranch }
    );
    if (!Array.isArray(data) && data.type === "file") {
      existingSha = data.sha;
      existingContent = Buffer.from(data.content, "base64").toString("utf-8");
    }
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status !== 404) throw err;
  }

  if (existingContent === desiredContent) {
    return false;
  }

  await octokit.request("PUT /repos/{owner}/{repo}/contents/{path}", {
    owner,
    repo,
    path: WORKFLOW_PATH,
    message: existingSha
      ? "Update FeedbackIQ agent workflow"
      : "Add FeedbackIQ agent workflow",
    content: desiredBase64,
    branch: defaultBranch,
    ...(existingSha ? { sha: existingSha } : {}),
  });
  return existingSha === null;
}

export async function ensureSecretSet(
  octokit: Octokit,
  owner: string,
  repo: string
): Promise<void> {
  const anthropicKey = process.env.ANTHROPIC_API_KEY;
  if (!anthropicKey) {
    throw new Error("ANTHROPIC_API_KEY is not set in the environment");
  }

  await sodium.ready;

  const { data: publicKeyData } = await octokit.request(
    "GET /repos/{owner}/{repo}/actions/secrets/public-key",
    { owner, repo }
  );

  const binKey = sodium.from_base64(
    publicKeyData.key,
    sodium.base64_variants.ORIGINAL
  );
  const binSecret = sodium.from_string(anthropicKey);
  const encrypted = sodium.crypto_box_seal(binSecret, binKey);
  const encryptedBase64 = sodium.to_base64(
    encrypted,
    sodium.base64_variants.ORIGINAL
  );

  await octokit.request(
    "PUT /repos/{owner}/{repo}/actions/secrets/{secret_name}",
    {
      owner,
      repo,
      secret_name: SECRET_NAME,
      encrypted_value: encryptedBase64,
      key_id: publicKeyData.key_id,
    }
  );
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export interface WorkflowDispatchResult {
  dispatchedAt: Date;
  runId: number | null;
  runUrl: string | null;
}

export async function triggerWorkflow(
  octokit: Octokit,
  owner: string,
  repo: string,
  feedbackId: string,
  feedbackContent: string,
  sourceUrl: string | null,
  defaultBranch: string,
  callbackUrl: string,
  installationToken: string,
  justCreated: boolean = false
): Promise<WorkflowDispatchResult> {
  const callbackSecret = process.env.GITHUB_APP_WEBHOOK_SECRET;
  if (!callbackSecret) {
    throw new Error("GITHUB_APP_WEBHOOK_SECRET is not set");
  }

  const maxAttempts = justCreated ? 6 : 1;
  const dispatchedAt = new Date();

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    if (justCreated && attempt > 1) {
      await sleep(5000);
    }

    try {
      await octokit.request(
        "POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches",
        {
          owner,
          repo,
          workflow_id: "feedbackiq.yml",
          ref: defaultBranch,
          inputs: {
            feedback_id: feedbackId,
            feedback_content: feedbackContent,
            source_url: sourceUrl || "",
            default_branch: defaultBranch,
            callback_url: callbackUrl,
            callback_secret: callbackSecret,
            installation_token: installationToken,
          },
        }
      );

      const run = await findRunAfterDispatch(
        octokit,
        owner,
        repo,
        dispatchedAt
      );
      return {
        dispatchedAt,
        runId: run?.id ?? null,
        runUrl: run?.html_url ?? null,
      };
    } catch (err: unknown) {
      const status = (err as { status?: number }).status;
      if ((status === 422 || status === 404) && attempt < maxAttempts) {
        continue;
      }
      throw err;
    }
  }

  return { dispatchedAt, runId: null, runUrl: null };
}

async function findRunAfterDispatch(
  octokit: Octokit,
  owner: string,
  repo: string,
  dispatchedAt: Date
): Promise<{ id: number; html_url: string } | null> {
  const cutoff = new Date(dispatchedAt.getTime() - 10_000).toISOString();

  for (let attempt = 0; attempt < 4; attempt++) {
    await sleep(attempt === 0 ? 2500 : 3000);

    try {
      const { data } = await octokit.request(
        "GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs",
        {
          owner,
          repo,
          workflow_id: "feedbackiq.yml",
          event: "workflow_dispatch",
          per_page: 5,
          created: `>=${cutoff}`,
        }
      );

      const run = data.workflow_runs?.[0];
      if (run?.id) {
        return { id: run.id, html_url: run.html_url };
      }
    } catch {
      // retry
    }
  }
  return null;
}

export async function getWorkflowRunStatus(
  octokit: Octokit,
  owner: string,
  repo: string,
  runId: number
): Promise<{
  status: string | null;
  conclusion: string | null;
  htmlUrl: string;
} | null> {
  try {
    const { data } = await octokit.request(
      "GET /repos/{owner}/{repo}/actions/runs/{run_id}",
      { owner, repo, run_id: runId }
    );
    return {
      status: data.status,
      conclusion: data.conclusion,
      htmlUrl: data.html_url,
    };
  } catch (err: unknown) {
    const status = (err as { status?: number }).status;
    if (status === 404) return null;
    throw err;
  }
}
